apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: deploy-proj-fd58be252647
  labels:
    app: grafana
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.deploy-proj-fd58be252647:9090
        isDefault: true
