apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: deploy-proj-fd58be252647
  labels:
    app: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-deploy-proj-fd58be252647
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/proxy", "nodes/metrics", "services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics", "/metrics/cadvisor", "/metrics/resource"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-deploy-proj-fd58be252647
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-deploy-proj-fd58be252647
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: deploy-proj-fd58be252647
