apiVersion: v1
kind: Service
metadata:
  name: tailwind-dashboard-template
  labels:
    app: tailwind-dashboard-template
spec:
  type: NodePort
  selector:
    app: tailwind-dashboard-template
  ports:
  - port: 80
    targetPort: 8000
